using LiveCharts;
using LiveCharts.Wpf;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
/**
 *
 * @author Erin Jade Naidoo(ST10081245)
 */

//references
//code attribution
//Book Author: Andrew Troelsen & Phil Japikse
//Book Title: Pro C# 10 with.NET 6 Foundational Principles and Practices in Programming Eleventh Edition (prescribed textbook)

namespace RecipeAppWPF
{
    // Define a partial class for the PieChartWindow, which is a WPF Window
    public partial class PieChartWindow : Window
    {
        // Property to hold the series collection for the pie chart
        public SeriesCollection SeriesCollection { get; set; }

        // Constructor that takes a dictionary of food group percentages
        public PieChartWindow(Dictionary<string, double> foodGroupPercentages)
        {
            // Initialize the components of the window (generated by the designer)
            InitializeComponent();

            // Initialize the SeriesCollection property
            SeriesCollection = new SeriesCollection();

            // Loop through each key-value pair in the dictionary
            foreach (var kvp in foodGroupPercentages)
            {
                // Add a new PieSeries to the SeriesCollection for each food group
                SeriesCollection.Add(new PieSeries
                {
                    Title = kvp.Key, // Set the title of the series to the food group name
                    Values = new ChartValues<double> { kvp.Value }, // Set the value of the series to the food group percentage
                    DataLabels = true // Enable data labels to show the value on the chart
                });
            }

            // Set the DataContext of the window to this instance
            // This is used for data binding in XAML
            DataContext = this;
        }
    }
}
